vich_uploader:
    db_driver: orm

    mappings:
        moto:
            uri_prefix: '%moto_images%'
            upload_destination: '%kernel.project_dir%/public%moto_images%'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'id' }