vich_uploader:
    db_driver: orm

    mappings:
        moto:
            uri_prefix: '%moto_images%'
            upload_destination: '%kernel.project_dir%/public%moto_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer